In [1]:
import torch
import matplotlib.pyplot as plt 
import numpy as np

import cProfile
import pstats

import abc
import torch
import scipy.stats as stats
import math
from torch.optim import Adam
from torch import nn

from sklearn.metrics import accuracy_score, roc_auc_score

from sklearn.linear_model import LogisticRegression, LogisticRegressionCV

import numpy as np
import rpy2.robjects as ro
from rpy2.robjects import r,numpy2ri,NULL
from rpy2.robjects.packages import importr
import rpy2.robjects.packages as rpackages

# Utility function to check for missing packages and install them
def install_missing_r_packages(package_names):
    utils = rpackages.importr('utils')
    utils.chooseCRANmirror(ind=1)
    for package_name in package_names:
        if not rpackages.isinstalled(package_name):
            utils.install_packages(package_name)


/home/dxie/anaconda3/envs/misc10/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
torch.manual_seed(1)
n = 500
p = 100
X = torch.randn(n,p)
s = 2
b = torch.cat((torch.ones(s)*2,torch.zeros(p-s)))
b = b.type(torch.FloatTensor)
b = b.reshape([p,1])
mu = torch.matmul(X,b)
mu = mu.squeeze()
prob = torch.exp(mu)/(1+torch.exp(mu))
y = torch.bernoulli(prob)
print(torch.bincount(y.int()))

X_test = torch.randn(3000,p)
mu_test = torch.matmul(X_test,b).squeeze()
prob_test = torch.exp(mu_test)/(1+torch.exp(mu_test))
y_test = torch.bernoulli(prob_test)


tensor([231, 269])


In [4]:
from bayesregR import bayesregR
model = bayesregR(family='gaussian')
model.fit(X=X,y=y)
print(model.run_time)
print(model.predict_prob(X_test))
print(model.predict(X_test))
print(roc_auc_score(y_test, model.predict_prob(X_test)))

5.883323972993821
[0.7263486  0.64790374 0.64170527 ... 0.63829619 0.52434711 0.6347658 ]
[0.97617503 0.60983751 0.58277319 ... 0.56797673 0.09746551 0.55271731]
0.9091943034438804


In [3]:
from L0Learn import L0Learn
model = L0Learn(family='SquaredError')
model.fit(X=X,y=y)
print(model.run_time)
print(model.predict_prob(X_test))
print(model.predict(X_test))
print(roc_auc_score(y_test, model.predict_prob(X_test)))

0.09447211899532704
[0.94803805 0.56629368 0.51164393 ... 0.61679768 0.13671608 0.48984647]
[0.94803805 0.56629368 0.51164393 ... 0.61679768 0.13671608 0.48984647]
0.8815786374256609


In [5]:
from ncvregR import ncvregR
model = ncvregR(family="poisson")
model.fit(X=X,y=y)
print(model.run_time)
#print(model.predict_prob(X_test))
print(model.predict(X_test))
#print(roc_auc_score(y_test, model.predict_prob(X_test)))

0.7870190960020409
[1.06229862 0.4692922  0.50227659 ... 0.46782377 0.19271162 0.48961647]


In [8]:
from glmnetR import glmnetR
model = glmnetR(family='poisson')
model.fit(X=X,y=y)
print(model.run_time)
#print(model.predict_prob(X_test))
print(model.predict(X_test))
#print(roc_auc_score(y_test, model.predict_prob(X_test)))

0.32861370400496526
[0.87272984 0.52716271 0.55731624 ... 0.48406092 0.29066752 0.54838669]


In [10]:
from glmnetR import elasticnetR
model = elasticnetR(family='poisson')
model.fit(X=X,y=y)
print(model.run_time)
#print(model.predict_prob(X_test))
print(model.predict(X_test))
#print(roc_auc_score(y_test, model.predict_prob(X_test)))

1.9437661890042364
[0.78854362 0.54074854 0.56985342 ... 0.49441791 0.33720647 0.56052735]


In [4]:
from sparsevbR import sparsevbR
model = sparsevbR(family='linear')
model.fit(X=X,y=y)
print(model.run_time)
#print(model.predict_prob(X_test))
print(model.predict(X_test))
#print(roc_auc_score(y_test, model.predict_prob(X_test)))

0.4374337999979616
[1.85869097 1.70191449 1.26603029 ... 1.5751546  0.817264   1.13397128]


In [4]:
from varbvsR import varbvsR
model = varbvsR(family='gaussian')
model.fit(X=X,y=y)
print(model.run_time)
#print(model.predict_prob(X_test))
print(model.predict(X_test))
#print(roc_auc_score(y_test, model.predict_prob(X_test)))

0.29042159899836406
[0.99405417 0.59266723 0.62621786 ... 0.54434293 0.13376505 0.61502462]
